feat(stable:rbac-manager): Upgrade rbac-manager to latest version
reactiveops/charts pull request #100
Opened 2019-07-11 08:23 UTC by oxyno-zeta

Upgrade rbac-manager to latest version and some readability on README and values.

2019-07-11 13:57 UTC, sudermanjr commented on stable/rbac-manager/Chart.yaml
> +version: 1.1.3
Since this is a minor version change to the underlying app, can you please make this a minor version change in the chart?

2019-07-11 14:24 UTC, sudermanjr requested changes
Since this is a minor version change to the underlying app, can you please make this a minor version change in the chart? I'm thiking 1.2.0 would be appropriate here.

2019-07-12 06:47 UTC, oxyno-zeta commented
Of course I can :) . Not a problem.
This is done.

2019-07-12 14:37 UTC, sudermanjr approved these changes
Thanks!

2019-07-12 14:37 UTC, merged