Update tested k8s versions to 1.23-1.25
reactiveops/charts pull request #1086
Opened 2023-02-08 15:46 UTC by rbren

**Why This PR?**
_a short description of why this PR is needed_

We're behind by a few versions on our k8s testing.

Fixes #

**Changes**
Changes proposed in this pull request:
* Change supported version range from 1.19-1.21 to 1.23-1.25

**Checklist:**

* [x] I have included the name of the chart in the title of this PR in square brackets i.e. `[stable/goldilocks]`.
* [x] I have updated the chart version in `Chart.yaml` following Semantic Versioning.
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] Any new values have been added to the README for the Chart, or `helm-docs --sort-values-order=file` has been run for the charts that support it.

2023-02-08 22:10 UTC, Azahorscak approved these changes

2023-02-09 15:18 UTC, sudermanjr requested changes

2023-02-09 15:18 UTC, sudermanjr commented on .circleci/config.yml
> +  rok8s11: fairwinds/rok8s-scripts@dev:sudermanjr/update-kind-0.16.0
```suggestion
  rok8s11: fairwinds/rok8s-scripts@v11
```

2023-02-09 15:19 UTC, sudermanjr approved these changes

2023-02-09 15:20 UTC, rbren commented on .circleci/config.yml
> +  rok8s11: fairwinds/rok8s-scripts@v11
```suggestion
  rok8s11: fairwinds/rok8s-scripts@11
```

2023-02-09 15:52 UTC, sudermanjr approved these changes

2023-02-09 17:23 UTC, merged