[VPA/stable] Add configurable value for tests.securityContext
reactiveops/charts pull request #1144
Opened 2023-04-14 15:18 UTC by davidblum

**Why This PR?**

This PR enables configuration for securityContext in the pods run as helm tests.

Fixes https://github.com/FairwindsOps/charts/issues/1143

**Changes**
Changes proposed in this pull request:

* add configuration for securityContext for vpa/templates/tests

**Checklist:**

* [ ] I have included the name of the chart in the title of this PR in square brackets i.e. `[stable/goldilocks]`.
* [ ] I have updated the chart version in `Chart.yaml` following Semantic Versioning.
* [ ] Any new values are backwards compatible and/or have sensible default.
* [ ] Any new values have been added to the README for the Chart, or `helm-docs --sort-values-order=file` has been run for the charts that support it.

2023-04-14 15:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/FairwindsOps/charts?pullRequest=1144) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/FairwindsOps/charts?pullRequest=1144) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/FairwindsOps/charts?pullRequest=1144) it.</sub>

2023-04-14 15:22 UTC, sudermanjr approved these changes
Looks great, thanks! 

Once the tests pass and the CLA is signed we can get this merged.

2023-04-14 15:23 UTC, sudermanjr commented
This might be helpful: https://github.com/FairwindsOps/charts#generating-docs

2023-04-14 15:55 UTC, davidblum commented
@sudermanjr CLA signed, docs updated. However its failing on a versioning issue. Should i have bumped the chart version in this PR? or does that happen automatically later?

2023-04-14 16:40 UTC, sudermanjr commented
The version bump you did looks correct. Not sure what's up with e2e tests.

2023-04-14 16:41 UTC, sudermanjr commented
Here's the error:

```
Error: UPGRADE FAILED: template: vpa/templates/tests/create-vpa.yaml:17:26: executing "vpa/templates/tests/create-vpa.yaml" at <.Values.tests.securityContext>: nil pointer evaluating interface {}.securityContext
```

2023-04-14 16:43 UTC, sudermanjr commented on stable/vpa/templates/tests/create-vpa.yaml
> +        {{- toYaml .Values.tests.securityContext | nindent 8 }}
I would check the nindent value here. Quick guess is that it should be 6, but I'm not sure. (applies to other files too)

2023-04-17 17:12 UTC, davidblum commented
@sudermanjr I've tried a few variations, and your suggestion.

But I can't get this to pass CI. The change does work locally.

Any thoughts?

2023-05-15 17:30 UTC, sudermanjr commented
Apologies for losing track of this. Could you please bump the version again and I'll take a closer look?

2023-05-15 17:45 UTC, sudermanjr commented
Apologies for losing track of this. When I install with these values and then run `helm test` I am getting:

```
3m ▶ helm test vpa
W0515 11:44:16.313261   92803 warnings.go:70] unknown field "spec.containers[0].allowPrivilegeEscalation"
W0515 11:44:16.313275   92803 warnings.go:70] unknown field "spec.containers[0].capabilities"
W0515 11:44:16.313277   92803 warnings.go:70] unknown field "spec.containers[0].readOnlyRootFilesystem"
W0515 11:44:16.313280   92803 warnings.go:70] unknown field "spec.containers[0].runAsGroup"
W0515 11:44:16.313281   92803 warnings.go:70] unknown field "spec.containers[0].runAsNonRoot"
W0515 11:44:16.313283   92803 warnings.go:70] unknown field "spec.containers[0].runAsUser"
W0515 11:44:19.770536   92803 warnings.go:70] unknown field "spec.containers[0].allowPrivilegeEscalation"
W0515 11:44:19.770560   92803 warnings.go:70] unknown field "spec.containers[0].capabilities"
W0515 11:44:19.770565   92803 warnings.go:70] unknown field "spec.containers[0].readOnlyRootFilesystem"
W0515 11:44:19.770570   92803 warnings.go:70] unknown field "spec.containers[0].runAsGroup"
W0515 11:44:19.770574   92803 warnings.go:70] unknown field "spec.containers[0].runAsNonRoot"
W0515 11:44:19.770578   92803 warnings.go:70] unknown field "spec.containers[0].runAsUser"
```

2023-05-15 17:48 UTC, sudermanjr requested changes

2023-05-15 17:48 UTC, sudermanjr commented on stable/vpa/templates/tests/crd-available.yaml
> +      {{- toYaml .Values.tests.securityContext | nindent 6 }}
```suggestion
      {{- toYaml .Values.tests.securityContext | nindent 8 }}
```

2023-05-15 17:48 UTC, sudermanjr commented on stable/vpa/templates/tests/crd-available.yaml
> +      {{- toYaml .Values.tests.securityContext | nindent 6 }}
```suggestion
      {{- toYaml .Values.tests.securityContext | nindent 8 }}
```

2023-05-15 17:48 UTC, sudermanjr commented on stable/vpa/templates/tests/create-vpa.yaml
> +      {{- toYaml .Values.tests.securityContext | nindent 6 }}
```suggestion
      {{- toYaml .Values.tests.securityContext | nindent 8 }}
```

2023-05-15 17:48 UTC, sudermanjr commented on stable/vpa/templates/tests/metrics.yaml
> +      {{- toYaml .Values.tests.securityContext | nindent 6 }}
```suggestion
      {{- toYaml .Values.tests.securityContext | nindent 8 }}
```

2023-05-15 17:48 UTC, sudermanjr commented on stable/vpa/ci/test-values.yaml
> +        - "ALL"
Since this is set as default in values.yaml, this is actually unnecessary now.
```suggestion
```

2023-05-15 18:13 UTC, sudermanjr commented
I now get no errors locally, but still get this in the CI job. I'm really not sure what's causing that.

```
Error: UPGRADE FAILED: template: vpa/templates/tests/create-vpa.yaml:18:24: executing "vpa/templates/tests/create-vpa.yaml" at <.Values.tests.securityContext>: nil pointer evaluating interface {}.securityContext
```

2023-05-16 16:18 UTC, davidblum commented
@sudermanjr This is the exact issue(s) I ran into as well.

I'm not quite sure which is the source of truth, CI or local build? But I'm concerned that they don't line up...

2023-05-16 20:29 UTC, sudermanjr commented
My only guess is that the version of helm in our CI is outdated and doing something odd. I will look into it a bit

2023-05-16 20:58 UTC, sudermanjr commented
I think I figured it out. The chart testing procedure does a `helm install` of the _previous_ revision, and then it does a `helm upgrade --reuse-values` with the new version in order to ensure backward compatibility of values. So in this case, I think we need to wrap the security context in an `{{- if .Values.tests.securityContext }}` block in order to make the upgrade/test work.


you can reproduce this now by doing this:

```
# checkout master
helm install vpa stable/vpa --namespace vpa --create-namespace --values ci/test-values.yaml
helm test vpa -n vpa

# checkout your branch
helm upgrade vpa stable/vpa --namespace vpa --reuse-values
helm test vpa -n vpa
```

2023-05-16 21:38 UTC, sudermanjr requested changes

2023-05-16 21:38 UTC, sudermanjr commented on stable/vpa/templates/tests/crd-available.yaml
> +      {{- toYaml .Values.tests.securityContext | nindent 8 }}
```suggestion
      {{- if .Values.tests }}
      securityContext:
      {{- toYaml .Values.tests.securityContext | nindent 8 }}
      {{- end }}
```

2023-05-16 21:38 UTC, sudermanjr commented on stable/vpa/templates/tests/crd-available.yaml
> +      {{- toYaml .Values.tests.securityContext | nindent 8 }}
```suggestion
      {{- if .Values.tests }}
      securityContext:
      {{- toYaml .Values.tests.securityContext | nindent 8 }}
      {{- end }}
```

2023-05-16 21:38 UTC, sudermanjr commented on stable/vpa/templates/tests/create-vpa.yaml
> +      {{- toYaml .Values.tests.securityContext | nindent 8 }}
```suggestion
      {{- if .Values.tests }}
      securityContext:
      {{- toYaml .Values.tests.securityContext | nindent 8 }}
      {{- end }}
```

2023-05-16 21:38 UTC, sudermanjr commented on stable/vpa/templates/tests/metrics.yaml
> +      {{- toYaml .Values.tests.securityContext | nindent 8 }}
```suggestion
      {{- if .Values.tests }}
      securityContext:
      {{- toYaml .Values.tests.securityContext | nindent 8 }}
      {{- end }}
```

2023-05-16 21:47 UTC, sudermanjr approved these changes

2023-05-16 21:47 UTC, merged

2023-05-16 21:47 UTC, sudermanjr approved these changes

2023-05-16 21:58 UTC, sudermanjr commented
Thanks again for the contribution, and for staying engaged while we work through this!

2023-05-17 17:05 UTC, davidblum commented
@sudermanjr Oh man, that is a sneaky bug! Great find.

Thanks for your help and openness to this issue!