[stable/gemini] Add a few features to the chart
reactiveops/charts pull request #1175
Opened 2023-05-05 09:42 UTC by h4wkmoon

**Why This PR?**
This PR adds a few features to the chart: tolerations, nodeSelector, pod labels & annotations.

**Changes**
Changes proposed in this pull request:

*
*

**Checklist:**

* [x] I have included the name of the chart in the title of this PR in square brackets i.e. `[stable/goldilocks]`.
* [ ] I have updated the chart version in `Chart.yaml` following Semantic Versioning.
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] Any new values have been added to the README for the Chart, or `helm-docs --sort-values-order=file` has been run for the charts that support it.

2023-05-05 09:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/FairwindsOps/charts?pullRequest=1175) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/FairwindsOps/charts?pullRequest=1175) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/FairwindsOps/charts?pullRequest=1175) it.</sub>

2023-05-05 16:51 UTC, aslafy-z requested changes
Here's a little typo.

2023-05-05 16:51 UTC, aslafy-z commented on stable/gemini/README.md
> +| additionalpodLabels | object | `{}` | Additional labels added on pod |
```suggestion
| additionalPodLabels | object | `{}` | Additional labels added on pod |
```

2023-05-05 16:51 UTC, aslafy-z commented on stable/gemini/values.yaml
> +additionalpodLabels: {}
```suggestion
additionalPodLabels: {}
```

2023-05-05 18:17 UTC, aslafy-z commented on stable/gemini/values.yaml
> +# additionalpodLabels -- Additional labels added on pod
```suggestion
# additionalPodLabels -- Additional labels added on pod
```

2023-05-11 14:03 UTC, rbren approved these changes

2023-05-11 14:03 UTC, merged