[stable/polaris] Add Deployment annotations
reactiveops/charts pull request #1270
Opened 2023-07-25 06:10 UTC by yu-croco

**Why This PR?**
_a short description of why this PR is needed_

In order to add annotations to Deployments, I added custom values.

**Changes**
Changes proposed in this pull request:

* Add annotations to webhook/dashboard Deployments

**Checklist:**

* [ ] I have included the name of the chart in the title of this PR in square brackets i.e. `[stable/goldilocks]`.
* [ ] I have updated the chart version in `Chart.yaml` following Semantic Versioning.
* [ ] Any new values are backwards compatible and/or have sensible default.
* [ ] Any new values have been added to the README for the Chart, or `helm-docs --sort-values-order=file` has been run for the charts that support it.

2023-07-25 06:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/FairwindsOps/charts?pullRequest=1270) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/FairwindsOps/charts?pullRequest=1270) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/FairwindsOps/charts?pullRequest=1270) it.</sub>

2023-08-03 14:10 UTC, sudermanjr requested changes
Thanks for the PR! 

Since this adds functionality to the chart, can you please bump the minor version rather than the patch version? Also, can you please add values to the ci/test-values.yaml file to make sure we are covering this feature in testing?

2023-08-04 11:28 UTC, yu-croco commented
Hi @sudermanjr , thank you for your review.
I fixed at https://github.com/FairwindsOps/charts/pull/1270/commits/dca24a7494d7191a6db5b5361b7c9220e178570f 🙋

2023-08-08 17:00 UTC, sudermanjr approved these changes

2023-08-08 17:01 UTC, sudermanjr approved these changes
Thanks! I'll get a codeowner to review.

2023-08-08 17:05 UTC, rbren approved these changes

2023-08-08 17:06 UTC, merged