[stable/goldilocks] Use TopologySpreadConstraint from dashboard object in dashboard deployment
reactiveops/charts pull request #1282
Opened 2023-08-03 12:04 UTC by 3vanlock

**Why This PR?**
_The Goldilocks chart currently uses the `controller` TopologySpreadConstraints for the `dashboard` Deployment. It does not allow for unique component values in the TSC labelSelector._

Fixes #

**Changes**
Changes proposed in this pull request:

* Use the `dashboard` TopologySpreadConstraint in the `dashboard` Deployment template.

**Checklist:**

* [x] I have included the name of the chart in the title of this PR in square brackets i.e. `[stable/goldilocks]`.
* [x] I have updated the chart version in `Chart.yaml` following Semantic Versioning.
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] Any new values have been added to the README for the Chart, or `helm-docs --sort-values-order=file` has been run for the charts that support it.

2023-08-03 12:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/FairwindsOps/charts?pullRequest=1282) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/FairwindsOps/charts?pullRequest=1282) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/FairwindsOps/charts?pullRequest=1282) it.</sub>

2023-08-03 14:05 UTC, sudermanjr requested changes
Thanks for catching this! Will you please update the ci/test-values.yaml to include a topologySpreadConstraint for both the controller and the dashboard? That will make sure we have better test coverage for this feature.

2023-08-03 14:08 UTC, sudermanjr commented
Fixes #1283

2023-08-03 15:41 UTC, sudermanjr commented
Looks like in the testing environment we only have a single node, so the test values are causing a dashboard pod to sit pending. I ssh'ed into the job and found this:

```
kubectl -n goldilocks-h5xke8kp4w describe po goldilocks-h5xke8kp4w-dashboard-bb6bfb7d-t4z99

  Warning  FailedScheduling  3m6s  default-scheduler  0/1 nodes are available: 1 node(s) didn't match pod topology spread constraints (missing required label). preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling.

2023-08-03 15:42 UTC, 3vanlock commented
Ah, okay. I'll flip it to ScheduleAnyway.

2023-08-03 15:51 UTC, 3vanlock commented
@sudermanjr It appears to be an issue with the node label, not the pod selector. Would you mind describing the node and listing available labels?

2023-08-03 16:38 UTC, sudermanjr commented
Here you go:

```
Name:               e2e-control-plane
Roles:              control-plane
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=e2e-control-plane
                    kubernetes.io/os=linux
                    node-role.kubernetes.io/control-plane=
                    node.kubernetes.io/exclude-from-external-load-balancers=
Annotations:        kubeadm.alpha.kubernetes.io/cri-socket: unix:///run/containerd/containerd.sock
                    node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Thu, 03 Aug 2023 16:34:27 +0000
Taints:             <none>
Unschedulable:      false
```

2023-08-07 16:26 UTC, sudermanjr commented on stable/goldilocks/Chart.yaml
> +version: 7.1.1
```suggestion
version: 7.1.2
```

2023-08-07 17:20 UTC, sudermanjr commented
Weird. Seems like we're still getting `Warning  FailedScheduling  19s   default-scheduler  0/1 nodes are available: 1 node(s) didn't match pod topology spread constraints (missing required label). preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling.`

Maybe removing the test values for this particular feature will be the easiest route since we do only have one node for these tests.

2023-09-07 16:57 UTC, sudermanjr commented
@3vanlock would you mind rebasing this and then removing the test values so we can get it merged?

2023-10-12 21:57 UTC, closed without merging