[stable/vpa] Update securityContext defaults
reactiveops/charts pull request #1345
Opened 2023-10-13 12:20 UTC by bodgit

**Why This PR?**
We run Kyverno on our clusters which alerts if the various `securityContext` settings aren't explicitly configured. Your Helm chart allows me to set/override these, but before I push this out to more clusters I figured it would be easier if the chart defaults were just updated.

As I'm only using the recommender, (for Goldilocks), I've not touched the `updater` or `admissionController` sections. I'm guessing these would probably be fine to have the same changes applied so can update the PR if desired.

**Changes**
Changes proposed in this pull request:

* Update recommender.podSecurityContext defaults to include `seccompProfile`.
* Update recommender.securityContext defaults to set `readOnlyRootFilesystem`, `allowPrivilegeEscalation` & `capabilities`.

**Checklist:**

* [x] I have included the name of the chart in the title of this PR in square brackets i.e. `[stable/goldilocks]`.
* [x] I have updated the chart version in `Chart.yaml` following Semantic Versioning.
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] Any new values have been added to the README for the Chart, or `helm-docs --sort-values-order=file` has been run for the charts that support it.

2023-10-13 12:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/FairwindsOps/charts?pullRequest=1345) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/FairwindsOps/charts?pullRequest=1345) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/FairwindsOps/charts?pullRequest=1345) it.</sub>

2023-10-23 21:41 UTC, sudermanjr requested changes
Since this changes default values, I would rather see a minor version change.

Also, if you don't mind keeping it consistent across all three deployments, I would also prefer that. Thanks!

2023-10-24 10:08 UTC, bodgit commented
@sudermanjr done

2024-01-12 11:23 UTC, bodgit commented
@sudermanjr ping

2024-01-17 15:15 UTC, sudermanjr approved these changes

2024-01-17 15:32 UTC, merged