Monitoring all namespaces out of the box
reactiveops/charts pull request #1509
Opened 2024-07-14 20:55 UTC by xogoodnow

Updated chart version

**Why This PR?**
Most users would want to monitor all namespaces within their cluster.

**Changes**
Changes proposed in this pull request:

Adding how to monitor all namespaces right out of the box in values file of goldilocks chart

**Checklist:**

* [ ] I have included the name of the chart in the title of this PR in square brackets i.e. `[stable/goldilocks]`.
* [ ] I have updated the chart version in `Chart.yaml` following Semantic Versioning.
* [ ] Any new values are backwards compatible and/or have sensible default.
* [ ] Any new values have been added to the README for the Chart, or `helm-docs --sort-values-order=file` has been run for the charts that support it.

2024-07-14 20:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/FairwindsOps/charts?pullRequest=1509) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/FairwindsOps/charts?pullRequest=1509) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/FairwindsOps/charts?pullRequest=1509) it.</sub>

2024-08-08 12:06 UTC, xogoodnow commented
Hi, @sudermanjr
Please let me know if there is an issue with this MR
Cheers

2024-08-08 12:09 UTC, xogoodnow commented
Hi @sudermanjr,
Please let me know if there is something wrong with this MR
Cheers

2024-09-20 21:51 UTC, sudermanjr commented on stable/goldilocks/values.yaml
> +  # controller.flags -- A map of additional flags to pass to the controller. For monitoring all namespaces out of the box, add the follwoing flag "on-by-default: true"
```suggestion
  # controller.flags -- A map of additional flags to pass to the controller. For monitoring all namespaces out of the box, add the following flag "on-by-default: true"
```

2024-09-20 21:51 UTC, sudermanjr commented on stable/goldilocks/values.yaml
> +  # dashboard.flags -- A map of additional flags to pass to the dashboard. For monitoring all namespaces out of the box, add the follwoing flag "on-by-default: true".
```suggestion
  # dashboard.flags -- A map of additional flags to pass to the dashboard. For monitoring all namespaces out of the box, add the following flag "on-by-default: true".
```

2024-09-20 21:51 UTC, sudermanjr approved these changes
Thanks!

2024-09-20 21:56 UTC, sudermanjr requested changes
Please update the readme per the contributing guide - https://github.com/FairwindsOps/charts/blob/master/CONTRIBUTING.md#documentation

2024-09-22 19:37 UTC, xogoodnow commented
Hi @sudermanjr, 
Readme file is updated.
If there is anything else please let me know.
Cheers

2024-10-01 04:24 UTC, sudermanjr approved these changes

2024-10-01 04:27 UTC, merged