Fix goldilocks flags, add to insights-agent
reactiveops/charts pull request #159
Opened 2019-11-04 22:21 UTC by rbren

Can break out the goldilocks change if you prefer Andy

2019-11-04 22:22 UTC, sudermanjr commented on stable/insights-agent/requirements.yaml
> +    version: 1.1.1
Seems like at least a minor version bump for the change in Goldilocks to v2 and enabling it by default.

2019-11-04 22:24 UTC, sudermanjr commented
You might have to separate these PRs just to get the linter to pass. The Goldilocks bump in insights can't pull the new version of goldilocks because it doesn't exist yet.

2019-11-04 22:28 UTC, makoscafee approved these changes

2019-11-05 00:04 UTC, sudermanjr requested changes
Not sure why, but the e2e tests are not getting any output whatsoever on this chart:

```
Installing chart with values file 'stable/insights-agent/ci/test-values.yaml'...

Too long with no output (exceeded 10m0s)
```

2019-11-06 18:37 UTC, sudermanjr approved these changes

2019-11-06 18:37 UTC, merged