updating letsencrypt-setup chart version along with new apiVersion for use with cert-manager v11.0+
reactiveops/charts pull request #189
Opened 2019-12-03 21:01 UTC by lucasreed

2019-12-03 21:14 UTC, sudermanjr commented
What's the process for upgrading this chart? Is it expected that we will update the resources as part of the upgrade to v0.11+ and then this chart will run smoothly?

2019-12-03 21:14 UTC, sudermanjr commented
What's the process for upgrading this chart? Is it expected that we will update the resources as part of the upgrade to v0.11+ and then this chart will run smoothly?

2019-12-03 21:31 UTC, lucasreed commented
Yes, during the upgrade of cert-manager we take a backup of all the custom resources that cert-manager owns (including ClusterIssuers) and manually update the apiVersion and re-post them at the end. In fact, as I typed that out I think I ought to test that part too. I'll do that.

2019-12-03 21:32 UTC, lucasreed commented
If recreating the ClusterIssuers during the cert-manager upgrade using backed-up resource definitions breaks helm, it would be fine to leave ClusterIssuers out of the backup and run this new chart after cert-manager is at v0.11.X

2019-12-03 21:41 UTC, sudermanjr approved these changes

2019-12-05 18:41 UTC, sudermanjr requested changes
Can we add a section to the readme that just mentions the upgrade process? I would be worried about people just bumping the version.

Maybe we should consider a major version bump on the chart for this to indicate that?

2019-12-05 21:43 UTC, sudermanjr commented on incubator/letsencrypt-setup/README.md
> +Please follow upgrade instructions [located here](https://github.com/FairwindsOps/docs-engineering/blob/master/how/cert-manager.md)
```suggestion
```

2019-12-05 21:44 UTC, sudermanjr approved these changes
Approved once link is fixed. Thanks!!!!!!

2019-12-06 18:57 UTC, merged