changes for astro chart 1.0.0
reactiveops/charts pull request #199
Opened 2019-12-12 22:24 UTC by lucasreed

- changed config value names starting with "controller" to start with "deployment" instead
- added permissions to coordination api for leader election
- made rbac a toplevel config value
- made replicas configurable
- added a command to the container spec to allow specification of an argument
- updated chart version to 2.0.0
- default img version to 1.5.0

I think after this is merged we can open a PR to move this chart into `stable/`

2019-12-13 00:48 UTC, sudermanjr requested changes
Can you please put a note about the values changes when upgrading from <v1 to 1.0.0+ ? This might break any existing installs.

In addition, can you please update the CODEOWNERS file at the root of the repo to make the Astro Codeowners the same for the chart? This will be a requirement for going to stable.

2019-12-16 14:03 UTC, mjhuber commented
I incremented `image.tag` to `v1.5.2` to get an important bug fix in this update

2020-01-03 19:04 UTC, lucasreed commented
Just making it back to this. I added documentation to the README for the changed values and squashed down to a single commit with all the changes.

2020-01-10 15:28 UTC, sudermanjr approved these changes

2020-01-10 15:29 UTC, merged