[helm-release-pruner] Fix service account name
reactiveops/charts pull request #204
Opened 2020-01-09 19:59 UTC by rbren

2020-01-15 14:12 UTC, coreypobrien requested changes
I think what we really want here is
a) By default, the chart uses a generated name that includes the release
b) If job.serviceAccountName is specified, we use that instead and we don't generate a service account (serviceAccountName would be an override essentially to use something existing)

2020-02-05 17:21 UTC, rbren commented
I had to duplicate some of the logic in _helpers.tpl (copying the `fullname` logic over to `serviceaccount`). `template` doesn't seem to play nicely with sprig functions...a couple things I tried that didn't work:
 
In the yaml files:
```
{{ .Values.serviceAccountName | default template helm-release-pruner.fullname }}
```

In _helpers.tpl:
```
{{- define "helm-release-pruner.serviceaccount" }}
{{- if .Values.serviceAccountName }}
{{- .Values.serviceAccountName }}
{{ template "helm-release-pruner.fullname" . }}
{{- else }}
{{- end }}

Any ideas on how to do this better?

2020-02-05 17:27 UTC, sudermanjr commented
I usually just do it like this:

https://github.com/FairwindsOps/charts/blob/507d676c2043d2680fe9f2621bd1785103063be7/stable/goldilocks/values.yaml#L22-L24

https://github.com/FairwindsOps/charts/blob/507d676c2043d2680fe9f2621bd1785103063be7/stable/goldilocks/templates/controller-deployment.yaml#L26-L30

2020-02-11 21:01 UTC, sudermanjr commented
@rbren Not sure if you wanted to change this, or if you are good to go.

2020-03-02 20:22 UTC, rbren commented
Oops sorry, lost track of this. Will take a look at your suggestion Andy

2020-03-05 21:13 UTC, bbensky approved these changes
LGTM

2020-03-16 21:12 UTC, rbren commented
@coreypobrien looks like I'm blocked pending your :rubberstamp:

2020-03-17 00:20 UTC, sudermanjr commented on incubator/helm-release-pruner/values.yaml
> +    # name: ExistingServiceAccountName
Normally it's better to leave this uncommented so that you can pass a `helm lint --strict`. Just a note for future reference, non-blocking.

2020-03-17 00:20 UTC, sudermanjr approved these changes

2020-03-17 00:21 UTC, merged