adding configurable-hpa chart
reactiveops/charts pull request #297
Opened 2020-05-14 23:03 UTC by crmejia

**Why This PR?**
Adding configurable-hpa as a tool that a client wants.

**Changes**
Changes proposed in this pull request:
* new chart

**Checklist:**

* [x] I have updated the chart version in `Chart.yaml` following Semantic Versioning.
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] Any new values have been added to the README for the Chart, or helm-docs has been run for the charts that support it.

2020-05-15 13:56 UTC, transient1 commented
Looks fine to me. Have you tested this anywhere?

2020-05-15 15:27 UTC, crmejia commented
No, I have not.

2020-05-19 16:12 UTC, sudermanjr requested changes
The linter failed with:

```
incubator/configurable-hpa/Chart.yaml
  7:20      error    no new line character at the end of file  (new-line-at-end-of-file)
```

2020-05-19 16:13 UTC, sudermanjr commented
Also, @crmejia, why are you not using the chart the tool creators wrote?

https://github.com/postmates/configurable-hpa/tree/master/deployment/helm/configurable-hpa

2020-05-22 18:22 UTC, ejether commented
I think we decided not to add this chart right now. . re-open if I misunderstood.

2020-05-22 18:22 UTC, closed without merging