add priorityclass
reactiveops/charts pull request #369
Opened 2020-10-01 09:02 UTC by dza89

**Why This PR?**
Add priorityclass option for all pods

Fixes #

**Changes**
Changes proposed in this pull request:

Priorityclass added

**Checklist:**

* [x ] I have updated the chart version in `Chart.yaml` following Semantic Versioning.
* [x ] Any new values are backwards compatible and/or have sensible default.
* [x ] Any new values have been added to the README for the Chart, or helm-docs has been run for the charts that support it.

2020-10-01 09:14 UTC, dza89 commented
Need some help with the check-docs, thought I fixed it but still error

2020-10-01 15:55 UTC, sudermanjr requested changes

2020-10-01 17:39 UTC, sudermanjr requested changes
One more version bump after pulling should take care of the helm-docs and helm-lint.

~Can you also add `priorityClassName: testPriority` to the ci/test-values.yaml file? This will make sure this value gets end-to-end tested.~ - Don't do that, it will fail the CI

2020-10-01 17:39 UTC, sudermanjr commented on stable/vpa/templates/admission-controller-deployment.yaml
> +      priorityClassName:
I think you'll need to add the value too:

```suggestion
      priorityClassName: {{ . }}
```

2020-10-05 23:08 UTC, sudermanjr approved these changes
Thanks!

2020-10-05 23:09 UTC, merged