[stable/vpa] Add probes and metrics ports
reactiveops/charts pull request #399
Opened 2020-11-27 15:51 UTC by omegas27

**Why This PR?**
_a short description of why this PR is needed_

This PR describes how to configure probes for the vpa chart as finding the correct port and paths needs users of the chart to dig into the vertical pod autoscaler pod

Fixes #

**Changes**
Changes proposed in this pull request:

* This PR adds probes to vpa components as well as describe the metrics port to allow scraping of the vpa component metrics

**Checklist:**

* [X] I have updated the chart version in `Chart.yaml` following Semantic Versioning.

2020-11-27 15:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/FairwindsOps/charts?pullRequest=399) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/FairwindsOps/charts?pullRequest=399) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/FairwindsOps/charts?pullRequest=399) it.</sub>

2020-11-30 18:40 UTC, sudermanjr requested changes
LGTM. Thanks!

In the future, we'll probably want to make these probes configurable, but this seems fine to me.

Only change requested is that we bump a minor version rather than patch. Changing probes could cause undesirable results or unexpected results on upgrade that I feel are better indicated by a minor version bump.

2020-12-02 09:53 UTC, omegas27 commented
I updated the chart version to 0.2.0

2020-12-02 18:20 UTC, sudermanjr approved these changes
Awesome. Thanks!!

2020-12-02 18:20 UTC, merged