Add automountServiceAccountToken to vpa certGen and cleanup
reactiveops/charts pull request #481
Opened 2021-05-05 15:09 UTC by joshuastern

**Why This PR?**
_a short description of why this PR is needed_

Add ability to specify automountServiceAccountToken on the vpa certGen and cleanup service accounts

Fixes #

**Changes**
Changes proposed in this pull request:

* Apply serviceAccount.create and serviceAccount.automountServiceAccountToken values to certGen and cleanup service accounts
*

**Checklist:**

* [ ] I have updated the chart version in `Chart.yaml` following Semantic Versioning.
* [X] Any new values are backwards compatible and/or have sensible default.
* [X] Any new values have been added to the README for the Chart, or helm-docs has been run for the charts that support it.

2021-05-05 18:14 UTC, sudermanjr requested changes
I'm hesitant to add the `if` block around these particular service accounts using that same value. That value is intended to control the long-lived service accounts for the hooks.

I do understand that some people will want to disable these service accounts, but I don't think overloading that value is the right way to do that.

If you can elaborate on your use-case, maybe we can come up with a different plan

2021-05-05 18:16 UTC, joshuastern commented
> I'm hesitant to add the `if` block around these particular service accounts using that same value. That value is intended to control the long-lived service accounts for the hooks.
> 
> I do understand that some people will want to disable these service accounts, but I don't think overloading that value is the right way to do that.
> 
> If you can elaborate on your use-case, maybe we can come up with a different plan

I really only care about the `automountServiceAccountToken` flag. I will remove the `if` conditional block.

2021-05-06 20:34 UTC, sudermanjr approved these changes

2021-05-06 20:35 UTC, merged

2021-05-06 20:43 UTC, j-land commented
@sudermanjr ???