lowering failureThreshold to 1 for fluentd-papertrail
reactiveops/charts pull request #49
Opened 2019-03-05 15:44 UTC by dosullivan

Based on finicky behavior we've seen with the papertrail plugin and fluentd, this lowers the failureThreshold to 1 for the fluentd daemonset's pods.

2019-03-05 15:47 UTC, sudermanjr requested changes
Looks fine, just needs a patch version bump.

2019-03-05 21:42 UTC, dosullivan commented
Bumped to 1.1.2.

2019-03-06 03:09 UTC, sudermanjr approved these changes

2019-03-06 03:09 UTC, sudermanjr commented
Thanks!

2019-03-06 15:50 UTC, merged