enable to use custom repository for clean up image
reactiveops/charts pull request #607
Opened 2021-11-09 08:40 UTC by yasintahaerol

**Why This PR?**
_a short description of why this PR is needed_
This image was pulling from a constant repository. Some developers or organizations want to use own their repository. It will be enabled to use custom repository by this feature.

Fixes #
It will be enabled to use custom repository by this feature.

**Changes**
Changes proposed in this pull request:

*
*

**Checklist:**

* [x] I have updated the chart version in `Chart.yaml` following Semantic Versioning.
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] Any new values have been added to the README for the Chart, or helm-docs has been run for the charts that support it.

2021-11-11 09:05 UTC, yasintahaerol commented
Hi, is everything okay?

2021-11-16 20:08 UTC, sudermanjr requested changes
This looks like it will not be backwards compatible with old versions of the values file.

I think we either need to use a different structure for the values, or bump the major version

2021-11-17 12:55 UTC, yasintahaerol commented
I think we should bump the major version.

2021-11-19 15:59 UTC, lucasreed requested changes
@yasintahaerol Agreed, can you please bump the version to `1.0.0`. Can you add a section to the readme documenting this breaking change as well? Thanks!

2021-11-26 13:43 UTC, yasintahaerol commented
hey @lucasreed. I think [this](https://app.circleci.com/pipelines/github/FairwindsOps/charts/3049/workflows/74985554-299e-439a-b3d2-84404080016f/jobs/16547?invite=true#step-103-30) error is not related to my commit. How should we proceed?

2022-01-13 15:28 UTC, sudermanjr requested changes

2022-01-13 15:28 UTC, sudermanjr commented on stable/vpa/Chart.yaml
> +version: 0.5.1
```suggestion
version: 1.0.0
```

2022-01-13 15:28 UTC, sudermanjr commented on stable/vpa/Chart.yaml
> +appVersion: 1.0.0
```suggestion
appVersion: 0.9.2
```

2022-01-13 16:40 UTC, sudermanjr requested changes

2022-01-13 16:40 UTC, sudermanjr commented on stable/vpa/values.yaml
> +      # admissionController.cleanupOnDelete.repository -- The location of the post-delete image
```suggestion
      # admissionController.cleanupOnDelete.image.repository -- The repository of the post-delete image
```

2022-01-13 16:40 UTC, sudermanjr commented on stable/vpa/values.yaml
> +      # admissionController.cleanupOnDelete.tag -- Overrides the image tag whose default is the chart appVersion
```suggestion
      # admissionController.cleanupOnDelete.image.tag -- Overrides the image tag whose default is the chart appVersion
```

2022-01-13 16:42 UTC, sudermanjr approved these changes

2022-01-13 18:05 UTC, lucasreed approved these changes

2022-01-13 18:05 UTC, merged