Update replicas for polaris dashboard and webhook deployment
reactiveops/charts pull request #677
Opened 2022-01-19 15:14 UTC by makoscafee

**Why This PR?**
_a short description of why this PR is needed_
This PR update dashboard and webhook deployment replicas to 2 to match new added rule enabled by default in polaris `deploymentMissingReplicas`

Fixes #
- Fixes `deploymentMissingReplicas` check error 
**Changes**
Changes proposed in this pull request:

* Update replicas for webhook and dashboard to `2`
*

**Checklist:**

* [ ] I have updated the chart version in `Chart.yaml` following Semantic Versioning.
* [ ] Any new values are backwards compatible and/or have sensible default.
* [ ] Any new values have been added to the README for the Chart, or helm-docs has been run for the charts that support it.

2022-01-20 02:04 UTC, sudermanjr requested changes

2022-01-20 02:04 UTC, sudermanjr commented on stable/polaris/Chart.yaml
> +appVersion: "5.0"
I don't think the version of polaris is changing, so we should keep this the same I think

2022-01-20 02:04 UTC, sudermanjr commented on stable/polaris/Chart.yaml
> +version: 5.0.0
This doesn't seem like a major change to the chart. Honestly it feels more like a patch version to me

2022-01-24 13:56 UTC, rbren approved these changes

2022-01-24 13:57 UTC, rbren commented
Should we try updating kube-hunter to get rid of that vuln?

2022-01-24 14:04 UTC, makoscafee commented
> Should we try updating kube-hunter to get rid of that vuln?

Sure, I can do that in this PR.

2022-02-17 15:27 UTC, merged