FWI-1244- Add  hyphens in the report names [insights-agent]
reactiveops/charts pull request #697
Opened 2022-02-07 15:03 UTC by makoscafee

**Why This PR?**
_a short description of why this PR is needed_
This is the final PR that merges all `Agent 2.0` changes to `master `branch
Fixes #

**Changes**
Changes proposed in this pull request:

* Add Hyphen back to all reports
* Rename resource metrics to prometheus-metrics
* Change admission failurePolicy to ignore 

**Checklist:**

* [x] I have updated the chart version in `Chart.yaml` following Semantic Versioning.
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] Any new values have been added to the README for the Chart, or `helm-docs --sort-values-order=file` has been run for the charts that support it.

2022-02-07 16:51 UTC, rbren reviewed
I think we will need to do this in two parts:
* release insights-admission 1.0.0
* release insights-agent 2.0.0 (with insights-admission 1.0.0 as a dependency)

To do that, you can create a new branch (say, `bm/admission-1-0`) and run
```
git checkout bm/agent-2-0 ./stable/insights-admission
```

2022-02-07 16:51 UTC, rbren commented on stable/insights-admission/Chart.yaml
> +version: 0.5.0
This should be 1.0.0

2022-02-07 16:51 UTC, rbren commented on stable/insights-agent/Chart.yaml
> +version: 1.18.0
This should be `2.0.0`

2022-02-07 16:54 UTC, rbren reviewed
We also need to update polaris to 5.0 right?

2022-02-07 17:35 UTC, makoscafee commented
> I think we will need to do this in two parts:
> 
> * release insights-admission 1.0.0
> * release insights-agent 2.0.0 (with insights-admission 1.0.0 as a dependency)
> 
> To do that, you can create a new branch (say, `bm/admission-1-0`) and run
> 
> ```
> git checkout bm/agent-2-0 ./stable/insights-admission
> ```

noted let me do that ..

2022-03-16 19:26 UTC, ivanfetch-fw commented
I'm aware that when I squash-merged a PR into this branch, via [this commit](https://github.com/FairwindsOps/charts/pull/697/commits/3fb0d90d73c0865f0af1d75373176d7b18268391) I referenced an incorrect insights-plugins PR in that commit note. I don't think this is worth reverting to fix, but wanted to comment here in case someone later finds my commit msg confusing.

2022-03-16 19:47 UTC, sudermanjr requested changes

2022-03-16 19:47 UTC, sudermanjr commented on stable/insights-agent/ci/test-values.yaml
> +  installPrometheusServer: true
This hasn't been changed in the requirements.yaml for the subchart, which is causing prometheus to get added unexpectedly

2022-03-21 19:28 UTC, sudermanjr requested changes, later dismissed

2022-03-21 19:28 UTC, sudermanjr commented on stable/insights-admission/Chart.yaml
> +version: 1.1.0
If we go ahead and bump this to 2.0.0, the CI tests will stop trying to do the upgrade check.

2022-03-28 14:33 UTC, rbren commented on stable/insights-agent/values.yaml
> +prometheus-metrics:
I think we need to change this tag to 1.0 now

2022-03-31 14:19 UTC, rbren commented on stable/insights-agent/README.md
> +`prometheus-metrics.installPrometheusServer` | Install a new Prometheus server instance for the proemetheus report | false
```suggestion
`prometheus-metrics.installPrometheusServer` | Install a new Prometheus server instance for the prometheus report | false
```

2022-04-05 17:17 UTC, sudermanjr requested changes

2022-04-05 17:17 UTC, sudermanjr commented on stable/insights-agent/Chart.yaml
> +version: 2.0.0-alpha
```suggestion
version: 2.0.0-alpha.0
```

2022-04-05 20:54 UTC, sudermanjr requested changes

2022-04-05 20:54 UTC, sudermanjr commented on stable/insights-agent/Chart.yaml
> +version: 2.0.0-rc1
Proper semver

```suggestion
version: 2.0.0-rc.1
```

2022-04-06 18:50 UTC, sudermanjr approved these changes

2022-04-06 19:42 UTC, rbren approved these changes

2022-04-06 19:56 UTC, merged