[aws-iam-authenticator] Make tolerations and nodeSelector configurable via values
reactiveops/charts pull request #729
Opened 2022-02-28 14:05 UTC by Nick-Triller

**Why This PR?**
As outlined in [KEP-2067](https://github.com/kubernetes/enhancements/tree/master/keps/sig-cluster-lifecycle/kubeadm/2067-rename-master-label-taint), the Kubernetes organisation deems the word "master" as offensive and works on replacing it with "control plane". Consequently, Kubernetes provisioning tools such as kubeadm and kops are replacing the names of taints and tolerations. `node-role.kubernetes.io/master` is replaced with `node-role.kubernetes.io/control-plane`, e.g. in this [kops PR](https://github.com/kubernetes/kops/pull/10397) or in the PRs linked to this [kubeadm issue](https://github.com/kubernetes/enhancements/issues/2067).

aws-iam-authenticator hardcodes master toleration and nodeSelector in it's helm chart. The toleration and nodeSelector do not work in clusters that use the new node label and taint naming. I would like to make the nodeSelector and tolerations configurable via chart values to solve this problem.

The original hardcoded values were set as default values to keep full backwards compatibility.

**Changes**
Changes proposed in this pull request:
* Make `tolerations` and `nodeSelector` configurable via values.yaml

**Checklist:**

* [x] I have updated the chart version in `Chart.yaml` following Semantic Versioning.
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] Any new values have been added to the README for the Chart, or `helm-docs --sort-values-order=file` has been run for the charts that support it.

2022-02-28 14:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/FairwindsOps/charts?pullRequest=729) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/FairwindsOps/charts?pullRequest=729) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/FairwindsOps/charts?pullRequest=729) it.</sub>

2022-02-28 15:18 UTC, sudermanjr requested changes
This looks great, thanks for the updates! 

I don't think the tests are going to pass for this one due to the nature of the chart, so we'll ignore those. I tested the changes locally and they seem fine.

Only remaining bit is to sign the CLA and we're good to go. Thanks again!

2022-02-28 16:09 UTC, ntriller-plaid commented
Awesome, thank you for the fast review! I will sign the CLA once it has been cleared by my employer.

2022-03-03 08:47 UTC, Nick-Triller commented
@sudermanjr ✅  CLA signed

2022-03-03 20:40 UTC, sudermanjr approved these changes

2022-03-03 20:40 UTC, merged