[stable/vpa] Allow specifying custom key/paths for the vpa-tls-cert
reactiveops/charts pull request #752
Opened 2022-03-17 20:34 UTC by aperullo

Fixes #751 

**Why This PR?**
This PR allows certificates created by means other than the admission-controllers [certgen](https://github.com/FairwindsOps/charts/blob/master/stable/vpa/templates/admission-controller-certgen.yaml) job to be mapped into the admission-controller pod. As it stands, any secret not following the format created by certgen with not be usable. This includes the official [kubernetes/tls-secret](https://kubernetes.io/docs/concepts/configuration/secret/#tls-secrets) format. 

**Changes**
Changes proposed in this pull request:

* Add a `tlsSecretKeys` field to allow mapping secret keys to their correct paths within the container. 
* Include the example commented out, a common practice in helm charts, that shows what the correct paths are. 
* Default this new field to empty to maintain backwards-compatibility.

**Checklist:**

* [x] I have included the name of the chart in the title of this PR in square brackets i.e. `[stable/goldilocks]`.
* [x] I have updated the chart version in `Chart.yaml` following Semantic Versioning.
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] Any new values have been added to the README for the Chart, or `helm-docs --sort-values-order=file` has been run for the charts that support it.

2022-03-17 20:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/FairwindsOps/charts?pullRequest=752) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/FairwindsOps/charts?pullRequest=752) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/FairwindsOps/charts?pullRequest=752) it.</sub>

2022-03-17 20:41 UTC, sudermanjr requested changes
Thanks for the contribution!

I left a small nit on the version number, but other than that seems great.

2022-03-17 20:41 UTC, sudermanjr commented on stable/vpa/Chart.yaml
> +version: 1.3.2
```suggestion
version: 1.3.0
```

2022-03-17 21:33 UTC, aperullo commented on stable/vpa/Chart.yaml
> +version: 1.3.2
Whoops that was silly of me. Fixed

2022-03-18 13:44 UTC, sudermanjr approved these changes

2022-03-18 13:44 UTC, merged