Adding BasePath functionality to [stable/goldilocks]
reactiveops/charts pull request #828
Opened 2022-05-25 22:10 UTC by lukerogers

**Why This PR?**
If my other PR to Goldilocks (https://github.com/FairwindsOps/goldilocks/pull/471) is approved, this would extend the functionality of adding a BasePath to Goldilocks. I didn't update the chart version as the code hasn't been merged yet and needs a new release version before updating.

**Changes**
Changes proposed in this pull request:

*Add BasePath functionality

**Checklist:**

* [ X ] I have included the name of the chart in the title of this PR in square brackets i.e. `[stable/goldilocks]`.
* [ ] I have updated the chart version in `Chart.yaml` following Semantic Versioning.
* [ X ] Any new values are backwards compatible and/or have sensible default.
* [ X ] Any new values have been added to the README for the Chart, or `helm-docs --sort-values-order=file` has been run for the charts that support it.

2022-05-25 22:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/FairwindsOps/charts?pullRequest=828) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/FairwindsOps/charts?pullRequest=828) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/FairwindsOps/charts?pullRequest=828) it.</sub>

2022-07-07 23:55 UTC, sudermanjr requested changes
The other PR has been released, so I think we just need a version bump here

2022-07-11 22:39 UTC, lukerogers commented
I just bumped the version

2022-07-12 21:22 UTC, sudermanjr approved these changes

2022-07-12 21:32 UTC, merged