[stable/vpa] securityContext on admission controller cleanup
reactiveops/charts pull request #966
Opened 2022-10-12 12:55 UTC by adavid44

**Why This PR?**
  Handle securityContext on cleanup pod
  
  Fixes #
  
  **Changes**
Changes proposed in this pull request:

  * Add the admissionController.cleanupOnDelete.securityContext block for certgen pod
  *
  
  **Checklist:**
  
  * [x] I have included the name of the chart in the title of this PR in square brackets i.e. `[stable/goldilocks]`.
  * [x] I have updated the chart version in `Chart.yaml` following Semantic Versioning.
  * [x] Any new values are backwards compatible and/or have sensible default.
  * [x] Any new values have been added to the README for the Chart, or `helm-docs --sort-values-order=file` has been run for the charts that support it.

2022-11-09 14:01 UTC, nerzhul commented
We'd like to have this PR too as we don't permit to run with no security context on our side :)

2022-11-09 14:02 UTC, adavid44 commented
Hello :wave: 
Any update on this MR ?

2023-01-11 18:54 UTC, sudermanjr requested changes
Can you please bump the version again, and either add a default securityContext or add one to the ci/test-values.yaml file? This will ensure that we cover this with testing. Thanks!

2023-01-26 18:22 UTC, rbren approved these changes

2023-04-05 01:47 UTC, closed without merging